import {
    Activity,
    Archive,
    Building2,
    CircleCheck,
    Copy,
    Download,
    ExternalLink,
    Eye,
    FileText,
    History,
    Image,
    Inbox,
    LayoutDashboard,
    Mail,
    MessageSquare,
    Pause,
    Pencil,
    Play,
    Plus,
    RefreshCw,
    RotateCcw,
    Search,
    Settings,
    Trash2,
    Upload,
    Users,
    type LucideIcon,
} from 'lucide-react';

/**
 * The icons PHP can name out of the box. A curated set keeps the bundle small; apps add more via
 * createLodestoneApp({ icons }). The package itself needs 'inbox' (empty states), 'search' (no matches)
 * and 'layout-dashboard' (the default page icon).
 */
export const defaultIcons: Record<string, LucideIcon> = {
    activity: Activity,
    archive: Archive,
    building: Building2,
    'circle-check': CircleCheck,
    copy: Copy,
    download: Download,
    'external-link': ExternalLink,
    eye: Eye,
    'file-text': FileText,
    history: History,
    image: Image,
    inbox: Inbox,
    'layout-dashboard': LayoutDashboard,
    mail: Mail,
    'message-square': MessageSquare,
    pause: Pause,
    pencil: Pencil,
    play: Play,
    plus: Plus,
    'refresh-cw': RefreshCw,
    'rotate-ccw': RotateCcw,
    search: Search,
    settings: Settings,
    'trash-2': Trash2,
    upload: Upload,
    users: Users,
};
